<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body class="min-vh-100 d-flex flex-column">

    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="<?= $routeParser->urlFor('main') ?>">Анализатор страниц</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $routeParser->urlFor('main') ?>">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="<?= $routeParser->urlFor('urls.index') ?>">Сайты</a>
                </li>
            </ul>
        </nav>
        
        <?php if (count($flash) > 0): ?>
            <?php foreach ($flash as $type => $messages): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="alert alert-<?= $type === 'error' ? 'danger' : ($type === 'warning' ? 'warning' : 'success') ?>" role="alert">
                        <?= htmlspecialchars($message) ?>
                    </div>
                <?php endforeach ?>
            <?php endforeach ?>
        <?php endif ?>
    </header>

    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <h1>Сайт: <?= htmlspecialchars($url['name']) ?></h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td><?= htmlspecialchars($url['id']) ?></td>
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td><?= htmlspecialchars($url['name']) ?></td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td><?= htmlspecialchars($url['created_at']) ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form action="<?= $routeParser->urlFor('urls.checks', ['url_id' => $url['id']]) ?>" method="post">
                <input type="submit" class="btn btn-primary mb-3" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
               <tbody>
                  <tr>
                     <th>ID</th>
                     <th>Код ответа</th>
                     <th>h1</th>
                     <th>title</th>
                     <th>description</th>
                     <th>Дата создания</th>
                  </tr>
                  <?php foreach($checks as $check): ?>
                     <tr>
                        <td><?=$check['id']?></td>
                        <td><?=$check['status_code']?></td>
                        <td><?=$check['h1']?></td>
                        <td><?=$check['title']?></td>
                        <td><?=$check['description']?></td>
                        <td><?=$check['created_at']?></td>
                     </tr>
                  <?php endforeach?>
               </tbody>
            </table>
        </div>
    </main>

    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hh.ru/resume/1d1ee09cff0b3781950039ed1f30584e653070?hhtmFrom=resume_list" target="_blank">Илья Игоревич</a>
            </div>
        </div>
    </footer>

</body>
</html>

