<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайты</h1>

        <?php if (isset($error)) : ?>
            <div class="alert alert-danger" role="alert">
                <?= htmlspecialchars($error) ?>
            </div>
        <?php endif; ?>

        <?php if (isset($message)) : ?>
            <div class="alert alert-info" role="alert">
                <?= htmlspecialchars($message) ?>
            </div>
        <?php endif; ?>

        <?php if (isset($urls) && count($urls) > 0) : ?>
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                    <?php foreach ($urls as $url) : ?>
                        <tr>
                            <td><?= htmlspecialchars($url['id']) ?></td>
                            <td>
                                <a href="<?= $routeParser->urlFor('urls.show', ['id' => htmlspecialchars($url['id'])]) ?>"><?= htmlspecialchars($url['name']) ?></a>
                            </td>
                            <td><?= htmlspecialchars($url['created_at'] ?? '') ?></td>
                            <td><?= htmlspecialchars($url['status_code'] ?? '') ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>
</main>