<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <?php if (isset($error)) : ?>
                    <div class="alert alert-danger" role="alert">
                        <?= $error ?>
                    </div>
                <?php endif; ?>
                <?php if (isset($flashMessages)) : ?>
                    <?php foreach ($flashMessages as $type => $messages) : ?>
                        <?php foreach ($messages as $message) : ?>
                            <div class="alert alert-<?= $type ?>" role="alert">
                                <?= $message ?>
                            </div>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post" class="row">
                    <div class="col-8">
                        <?php if (!empty($errors) && isset($errors['name'])) : ?>
                            <input type="text" name="url[name]" class="form-control form-control-lg is-invalid" placeholder="https://www.example.com" value="<?= htmlspecialchars($url ?? '') ?>">
                            <?php foreach ($errors['name'] as $error) : ?>
                                <div class="invalid-feedback d-block">
                                    <?= $error ?>
                                </div>
                            <?php endforeach; ?>
                        <?php else : ?>
                            <input type="text" name="url[name]" class="form-control form-control-lg" placeholder="https://www.example.com" value="<?= htmlspecialchars($url ?? '') ?>">
                        <?php endif; ?>
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить" aria-label="Запустить проверку SEO анализатора страниц">
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>