<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Анализатор страниц помогает быстро и бесплатно проверить сайты на SEO-пригодность. Начните анализ уже сегодня!">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>

<body class="min-vh-100 d-flex flex-column">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="<?= $routeParser->urlFor('main') ?>">Анализатор страниц</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link <?= $currentRoute === 'main' ? 'active' : '' ?>" href="<?= $routeParser->urlFor('main') ?>">Главная</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link <?= $currentRoute === 'urls.index' ? 'active' : '' ?>" href="<?= $routeParser->urlFor('urls.index') ?>">Сайты</a>
            </li>
        </ul>
    </nav>
</header>

    <main class="flex-grow-1">
        <?= $content ?>
    </main>
    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hh.ru/resume/1d1ee09cff0b3781950039ed1f30584e653070?hhtmFrom=resume_list" target="_blank">Илья Игоревич</a>
            </div>
        </div>
    </footer>
</body>

</html>