name: my-check CI

on:
  - push

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: make install

      - name: Linter
        run: make lint